name: Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [testing, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black
        run: |
          ./scripts/run-black.sh

      - name: Run Flake8
        run: |
          ./scripts/run-flake8.sh

      - name: Run Isort
        run: |
          ./scripts/run-isort.sh
